name: Integration Test
on: [push]
jobs:
  build_multiple_files_with_options:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v6
      - name: Compile Test Files
        uses: BillPete/typst-action@dev
        with:
          source_file: |
            tests/valid.typ
            tests/math.typ
          options: |
            --deps=tests/deps.txt
      - name: Check for Existence of Output Files
        run: |
          test -e "tests/valid.pdf"
          test -e "tests/math.pdf"
          test -e "tests/deps.txt"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Output Files
          path: |
            tests/*.pdf
            tests/deps.txt
